### ISSUE TITLE
Issue with zoom in and out

### ISSUE THREAD

**Issue by kushal98** [tusharnankani/TSECHackathon#1]
Hey,

As of now the user can zoom in and out to unlimited extent. I think if there is some restriction in the upper and lower limit that would be great.

Thanks

**Comment by tusharnankani** [comment]
Hi @kushal98!

Thank you for pointing it out! 🤗

I have fixed it: added restriction to the fontSize. [FIX](https://github.com/tusharnankani/Swadeshi/commit/c34ef3d4500ae64378254425aec1f88272c06b5e)
