### ISSUE TITLE
OTP is Not Coming

### ISSUE THREAD

**Issue by kushal98** [tusharnankani/TSECHackathon#2]
Hey,

I tried logging in using my phone number but did not recieve the OTP. Can u check please?

Thanks

**Comment by tusharnankani** [comment]
HI @kushal98 
We haven't used any tool for OTP. Since, this is a prototype, the OTP message isn't sent to the number. Instead, a random 4 digit number is generated on the Console (on the website deployed) [Press `Ctrl + Shift + i`]

**Comment by kushal98** [comment]
Ok got it. But you should mention it in the docs or readme else anyone can get confused.
Also the website is not responsive so user can face difficulty.

Thanks

**Comment by tusharnankani** [comment]
Updated the README.md! 

Thank you!
